CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id CHAR(36) NOT NULL,
  client_id VARCHAR(64) NOT NULL,
  city VARCHAR(64) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  ts_utc DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_tx_client_ts ON transactions (client_id, ts_utc);

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id CHAR(36) NOT NULL,
  client_id VARCHAR(64) NOT NULL,
  rule_code VARCHAR(16) NOT NULL,        -- ALTO_VALOR, TEMPO_60s, GEO_10m
  details TEXT NOT NULL,
  ts_utc DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
